// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID        uuid.UUID
	Msisdn    string
	Content   string
	Sent      bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
